### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by pataquets**
Add Dockerfile to enable image building. Useful for development and tests under Docker workflow.
Using the official Python 3 image, latest tag. More info at https://hub.docker.com/_/python/
 
Just adding files, setting working dir and running install and build.
 
Build:
 
```
$ docker build -t nanodlna .
```
 
Run:
 
```
$ docker run --rm -it --net=host -v $HOME/Videos/:/media/:ro nanodlna play /media/myVideo.mp4
```
 
FYI, there's a still quicker to test, already built image on my Docker Hub. Test it by running:
 
```
$ docker run --rm -it --net=host -v $HOME/Videos/:/media/:ro pataquets/nano-dlna-src play /media/myVideo.mp4
```
 
Using `--rm` causes container it to be deleted after stop and `-it` makes the container not to go background and run interactively. Using `--net=host` to allow listening on local interfaces. Otherwise, you would need to map ports from Docker host to container.
To access host's local media, just mount directories inside the Docker container as above. Use as many `-v` switches as needed.
 
Optional improvement to come (maybe in another issue):
- Create an 'official', based on your repo, automated build at Docker Hub for the image: https://docs.docker.com/docker-hub/builds/ . Just requires a free Docker Hub account and a following a quick 'Create automated build' process. I'll be happy to help on it, if needed.

### CODE REVIEW

**Comment by pataquets** [comment]
@gabrielmagno: ping in case you don't get issue notifications

**Comment by gabrielmagno** [comment]
Awesome @pataquets !
Thank you for making the dockerfile. This is indeed very useful.

**Review by gabrielmagno — APPROVED** [review]

**Comment by pataquets** [comment]
Happy to help, @gabrielmagno. How about creating a public, official Docker image at Docker Hub built from source using DH's [Automated Builds](https://docs.docker.com/docker-hub/builds/)?
It's just a few minutes of registering and clicking to link DH to your GitHub repo. In no time you'll have another distribution method, no Python required, on any OS.

**Comment by gabrielmagno** [comment]
@pataquets Done: https://hub.docker.com/repository/docker/gabrielmagno/nano-dlna
Thank you again!

**Pull request merged**
