### PR TITLE
Code cosmetics and fixes

### PR DESCRIPTION
**Pull request by vuolter**
Full code cleanup according pep8 specs
Added flake8 test in travis
Better .gitignore
Updated setup.py (zip-safe flag to True + python 3.6 in classifiers)
Sorted imports

### CODE REVIEW

**Comment by gabrielmagno** [comment]
Thank you @vuolter! 
I'm just wondering the reason for the removal of the "requirements.txt" file.

**Comment by vuolter** [comment]
I removed it because I did not find a reason to keep it since the dependencies are always stored in the setup.py, but it's just a my point of view.

**Comment by vuolter** [comment]
@gabrielmagno News?

**Comment by gabrielmagno** [comment]
@vuolter I prefer to maintain the "requirements.txt" for now. Is it possible for you to edit your pull request and remove the commit regarding this?

**Comment by vuolter** [comment]
@gabrielmagno Sure, no probleam at all. I'll post the changes soon as I can. ;)

**Comment by vuolter** [comment]
@gabrielmagno Done.

**Pull request merged**
